### PR TITLE
Fixed some iOS 13 deprecations

### PR DESCRIPTION
**Pull request by ddaddy**

### CODE REVIEW

**Comment by rolandleth** [comment]
Hey, thank you for the contribution!

Have you also tested on versions prior to 13? By the looks of it, it should, it's basically the same code, but it doesn't hurt to check.

`windowScene` is available on any kind of projects, not just SwiftUI, right? Haven't played much (at all) with iOS 13 specific stuff.

**Comment by ddaddy** [comment]
Hey, no problem.

I've tested this on iOS 12 and works as it always did. I wrapped the windowScene code in `__IPHONE_OS_VERSION_MAX_ALLOWED` so it would still compile on older versions of Xcode.

I don't use Swift or SwiftUI myself either. I haven't done anything with UIWindowScene either, but windowScene is automatically there are part of the UIWindow in iOS 13, so it's all good.

I forgot one major thing from the initial pull request, I think it's now been added here.
iOS 13 changes the way modal's are presented and unless you specify for it to be full screen they are dismissible by dragging them down.

**Comment by rolandleth** [comment]
That makes sense. I will pull this and give it a go later today (latest tomorrow), merge and release a new pod version.

**Comment by ddaddy** [comment]
👍🏼
If you get a chance, could you see if you can utilise `viewwilltransitiontosize:withTransitionCoordinator:` instead of the statusBar notifications?
I think the tricky thing here is it’s called before a rotation is finished not after like the notifications.

**Comment by rolandleth** [comment]
I’ll try to find some. What would be the advantage, though?

**Comment by ddaddy** [comment]
`UIApplicationDidChangeStatusBarOrientationNotification` & `UIApplicationDidChangeStatusBarFrameNotification` are deprecated in iOS 13.

I've just had another look, and we might be able to just use `UIDeviceOrientationDidChangeNotification` instead of the above 2. It seems to work the same, but I'd rather you double checked it before I change it.

**Comment by rolandleth** [comment]
It looks OK, I'll merge, but I'll increase the minimum target to iOS 10 (the latest supported by Xcode), so a bit of your changes will be deleted, since we'll remove all the `LTHiOS8` logic.

I checked `viewwilltransitiontosize:withTransitionCoordinator:` as well and it appears to work properly 👍🏻

**Pull request merged**
