### PR TITLE
Offset log out button from left edge of the screen

### PR DESCRIPTION
**Pull request by tschmitz**

### CODE REVIEW

**Comment by rolandleth** [comment]
What's the reason behind this?

**Comment by tschmitz** [comment]
Without it, the log out button is pushed up directly against the edge of the screen. (See attached screenshots for comparison.)

simulator screen shot sep 14 2015 4 39 23 pm
simulator screen shot sep 14 2015 4 39 13 pm

**Comment by rolandleth** [comment]
I'm having the same problem on an app, but it's iOS 9-only. Can you check if this is the case as well, and add a check if so, please?

**Comment by tschmitz** [comment]
The screenshots were taken in the iOS 8.4 Simulator, and the behavior is the same there.

**Comment by rolandleth** [comment]
Oh, okay :)
Thanks!

**Pull request merged**
