### PR TITLE
Allow unlock with Touch ID optional

### PR DESCRIPTION
**Pull request by jnavarrom**

### CODE REVIEW

**Comment by rolandleth** [comment]
Hey, and thanks for the PR. There's a problem though:

screen shot 2016-01-19 at 11 25 18 am

**Comment by jnavarrom** [comment]
Oh, yes the problem is that the `_saveAllowUnlockWithTouchID` method is inside `#if !(TARGET_IPHONE_SIMULATOR)`. I will fix it now

**Comment by jnavarrom** [comment]
@rolandleth, can you take a look?

**Comment by rolandleth** [comment]
Oh, I'm sorry, I didn't receive any notifications for it. I will have a look tonight or tomorrow first thing.

**Comment by rolandleth** [comment]
Hmm, instead of moving those out the `#if` blocks, why not move everything else related to TouchID inside? I think the intentions and behavior would be more explicit.

**Comment by jnavarrom** [comment]
Ok, I will move all code related TouchID inside the block `#if` and I will add ```#if !(TARGET_IPHONE_SIMULATOR)
    _allowUnlockWithTouchID = [self _allowUnlockWithTouchID];
#endif``` in `_loadMiscDefaults`

Do you like this approach?

**Comment by rolandleth** [comment]
I'd say it better expresses the intent. It would need an `#else` branch too, to fallback on `YES`.

**Comment by jnavarrom** [comment]
I think that the value of `_allowUnlockWithTouchID` in the simulator is not relevant, but anyway in the
`#else` should be `_allowUnlockWithTouchID = NO`? Because in simulator you can not use TouchID

```Objective-C
#if !(TARGET_IPHONE_SIMULATOR)
    _allowUnlockWithTouchID = [self _allowUnlockWithTouchID];
#else
    _allowUnlockWithTouchID = NO;
#endif

**Comment by rolandleth** [comment]
Yupp, you're right, that is better. But since we have `if` and `else`, I'd go with `if condition` instead of `if !condition`.

**Comment by jnavarrom** [comment]
:+1:

**Comment by rolandleth** [comment]
Looks great, thanks!

**Pull request merged**
