### PR TITLE
Property to hide the right "cancel" button on the navigation bar

### PR DESCRIPTION
**Pull request by fabiosoft**
Useful property to hide or show right button on the navigation bar.

### CODE REVIEW

**Comment by rolandleth** [comment]
Looks great! Can you remove the `podspec` file please? There is one already, just not in the repo.

I'd prefer if you could remove the commit altogether, via an interactive `rebase`.

**Comment by fabiosoft** [comment]
@rolandleth why don't you want to include the podspec here? It's useful...

**Comment by rolandleth** [comment]
@fabiosoft It might be because there might be differences between tabs and spaces; can you check, please? @ivdma thanks for pointing out :)
As for the podspec file, I already keep all my podspec files grouped in the same folder, I don't see any real advantage to keep it in the repo.

**Comment by fabiosoft** [comment]
No adavantages? People can improve and try your control even before cocoapods updated verision comes out... and most of all can get the latest or "custom" version directly from git repo.
Anyway @rolandleth i removed the podspec file as you demanded.

**Comment by rolandleth** [comment]
@fabiosoft The idea is that whenever I accept a PR, I immediately update the file and push a new pod version - if the file exists in the repo, I have to trust contributors won't forget to update it, otherwise this goes back and forth until everything is properly done.

What's with that `Merge branch master`, with all of those `tab` to `spaces` conversions? The idea was to fix that line, not convert everything to `tabs`.

Also, the removal of the `podspec` file should have been done by removing the commit altogether, not by `revert`. You can find out how to do that [here](http://githowto.com/removing_commits_from_a_branch) or [here](http://stackoverflow.com/a/495352/793916).

I'm sorry, but at this point you have 7 commits, out of which 5 are not needed. I'd suggest opening a new branch instead of trying to fix the current one.

**Comment by fabiosoft** [comment]
ok, let's restart from scratch...

**Pull request closed without merging**
