### PR TITLE
Added Dutch (nl) & Added animation

### PR DESCRIPTION
**Pull request by vrwim**
Using the standard text in iOS Settings.

Animation similar to standard iOS & OS X

### CODE REVIEW

**Comment by vrwim** [comment]
Added animation too.

**Comment by rolandleth** [comment]
Thanks!

**Comment by vrwim** [comment]
I tried making multiple pull requests, but when I committed the animation, it immediately added it to this pull request. Is there a way to stop this? Is it because I selected master from my repo to yours?

**Comment by rolandleth** [comment]
Yes, you committed over the branch you pull requested with. Why? Everyone will like it :)

**Comment by vrwim** [comment]
Well now it's okay, but what if I commit something that you don't want to include? Is it only possible by creating another branch? Or can I stop a commit from being in a pull request? Sorry, git newb here :)

**Comment by rolandleth** [comment]
Now the pull request has been accepted. But if you will do 5 more commits and do another pull request, all of those will be in the PR. Or if you do 5 commits, change to a branch, do 2 more on that branch, all 7 will be in the PR. I don't think you can mark a single commit to not be included in a PR.

**Pull request merged**
