### PR TITLE
Remove the string "Enter Passcode", it is not used

### PR DESCRIPTION
**Pull request by jnavarrom**

### CODE REVIEW

**Comment by rolandleth** [comment]
Hey, thank you again!

Can you please update the CHANGELOG and Version as well, as per https://github.com/rolandleth/LTHPasscodeViewController/blob/master/.github/CONTRIBUTING.md?

**Comment by jnavarrom** [comment]
Hi @rolandleth ,

Will do

3.9.2
- Fixed a crash in demo project
- Removed unused string

^ Is it ok for you?

**Comment by rolandleth** [comment]
Yupp, looking great! I think `3.9.2` got reverted.

**Comment by jnavarrom** [comment]
Done

**Comment by rolandleth** [comment]
Awesome, thank you!

**Pull request merged**
